### ISSUE TITLE
wss not work

### ISSUE THREAD

**Issue by MRSteam** [ratchetphp/Pawl#16] opened 2015-02-19 15:27 UTC
"PHP message: PHP Catchable fatal error:  Argument 1 passed to Devristo\Phpws\Client\WebSocket::Devristo\Phpws\Client\{closure}() must be an instance of React\Stream\Stream, instance of React\SocketClient\SecureStream given, called in /var/www/*/vendor/react/promise/src/FulfilledPromise.php on line 24 and defined in /var/www/*/vendor/devristo/phpws/src/Devristo/Phpws/Client/WebSocket.php on line 95" while reading response header from upstream, client: *, server: *, request: "GET /api.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "*"

@cboden

**Comment by clue** [comment] 2015-02-19 15:33
This is caused by a BC break in react/socket-client (https://github.com/reactphp/socket-client/issues/21), suggested fix is in https://github.com/reactphp/socket-client/pull/25.

**Comment by MRSteam** [comment] 2015-02-19 16:05
Ups, my mistake, my issue was for phpws, not for ratchetphp/Pawl.
So, does ratchetphp/Pawl work with WSS correctly?

**Comment by cboden** [comment] 2015-02-19 16:09
@MRSteam Yup!

**Comment by clue** [comment] 2015-02-19 16:14
> Ups, my mistake, my issue was for phpws, not for ratchetphp/Pawl.

Duh :) Yup, this has indeed been fixed with #13.

**Comment by MRSteam** [comment] 2015-02-19 16:24
Wait please, I need some help from you!
My problem: I want to get some messages from websocket server and send some messages to it. Websocket server is not mine, i just need to talk with server. So I think I need only a websocket client, isn't it?
First question is why I need Ratchet (server) for work with Pawl (client)? (There are some strings like $connector = new Ratchet\Client\Factory($loop); in Pawl).

**Comment by cboden** [comment] 2015-02-19 16:27
Yes, you only need a WebSocket client.

Ratchet (server) is pulled in by Pawl dependencies because it needs the RFC6455 protocol parser. I'm working on separating this out to a separate repository, but for the time being Ratchet is a dependency. Ratchet (server) is not actually run in Pawl. 

As for the namespace, Pawl is under the Ratchet namespace+organization and was there before I came up with the name Pawl.

**Comment by MRSteam** [comment] 2015-02-19 16:44
I created a folder named "server", there I created a file named 'composer.json' with contents from https://github.com/ratchetphp/Ratchet/blob/master/composer.json then run "composer install", there are no errors. Everything seems okay. Then I tried to run my_test_server.php with contents of "A quick example".

And I get some errors: Interface 'Ratchet\MessageComponentInterface' not found

**Comment by MRSteam** [comment] 2015-02-19 16:46
I created a folder named "server", there I created a file named 'composer.json' with contents from https://github.com/ratchetphp/Ratchet/blob/master/composer.json then run "composer install", there are no errors. Everything seems okay. Then I tried to run my_test_server.php with contents of "A quick example".

And I get some errors: Interface 'Ratchet\MessageComponentInterface' not found

**Closed** 2015-02-20 12:34 UTC
