### ISSUE TITLE
Another SSL question

### ISSUE THREAD

**Issue by MrMoronIV** [ratchetphp/Pawl#72] opened 2018-02-01 14:05 UTC
```
$loop = React\EventLoop\Factory::create();
$reactConnector = new React\Socket\Connector($loop, [
	],
	[
	'allow_self_signed' => true, 
	'verify_peer'       => false,
	'verify_peer_name'  => false
	]
	);
$connector = new Ratchet\Client\Connector($loop, $reactConnector);

$connector('wss://'.$ip.':'.$socketPort, [], ['Origin' => 'http://localhost'])
->then(function(Ratchet\Client\WebSocket $conn) {
    $conn->on('message', function(\Ratchet\RFC6455\Messaging\MessageInterface $msg) use ($conn) {
        echo "Received: {$msg}\n";
        $conn->close();
    });

    $conn->on('close', function($code = null, $reason = null) {
        echo "Connection closed ({$code} - {$reason})\n";
    });

    $conn->send('Hello World!');
}, function(\Exception $e) use ($loop) {
    echo "Could not connect: {$e->getMessage()}\n";
    $loop->stop();
});

$loop->run();
```

> Result: Could not connect: Unable to complete SSL/TLS handshake: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed 

Running on PHP 7.2

The actual socket I try to connect to is running on the same server and is a very well working Ratchet socket with valid domain certificates.
I'm not sure what SSL settings I should pass on.
 
And yes, I read all the other SSL topics ;)

**Comment by clue** [comment] 2018-02-01 16:20
It looks like you're missing the `tls` key for your context passed to the `Connector`, see also https://github.com/reactphp/socket#connector 👍

**Comment by MrMoronIV** [comment] 2018-02-01 19:03
you mean 'tls' => true, in the connector ssl array? Didn't change a thing...

**Comment by clue** [comment] 2018-02-01 19:13
Straight from the documentation linked above:

```php
// allow insecure TLS connections
$connector = new Connector($loop, array(
    'tcp' => array(
        'bindto' => '192.168.0.1:0'
    ),
    'tls' => array(
        'verify_peer' => false,
        'verify_peer_name' => false
    ),
));
```

**Comment by MrMoronIV** [comment] 2018-02-01 19:37
that doesn't do much, same error as before:
`Could not connect: Unable to complete SSL/TLS handshake: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed `

**Comment by MrMoronIV** [comment] 2018-02-01 19:53
Follow up question, the connectoin seems to be closed immediately, 
` $conn->send('Hello World!');
is actually never sent to the server, any idea why that happens?
It just says connection closed (code 1000) normal closure

**Comment by MrMoronIV** [comment] 2018-02-01 20:05
My ratchet server has this function in the app (which works great when a browser is connected)
```
	public function onMessage(ConnectionInterface $conn, $msg) 
	{
		var_dump($msg);

```
the dump never gets called when i run the above pawl script

**Comment by mbonneau** [comment] 2018-05-22 23:35
@MrMoronIV It is hard to say what the problem is without more info.

Can you post the sources for your client?

**Comment by mbonneau** [comment] 2018-10-12 16:36
@MrMoronIV I am closing this because it is old. If you are still having issues, feel free to reopen.

**Closed by mbonneau** 2018-10-12 16:36 UTC

**Comment by mayanktiwaridotcom** [comment] 2020-05-24 14:01
@MrMoronIV I had exactly the same problem as you mentioned in this issue, and solved is when found this, but now i get `unable to write to stream: fwrite(): ssl operation failed with code 1` even though messages are being sent. can you share your working code so I can verify what did I miss. 

https://github.com/ratchetphp/Ratchet/issues/799#issuecomment-633223168

this is what I was doing originally before finding this thread.

**Comment by MrMoronIV** [comment] 2020-05-24 17:17
I opted to go with a NodeJS socket.io server instead, much better than PHP for a socket, and much easier to setup.

**Comment by khasman** [comment] 2021-10-03 10:45
Hi, I tried to integrate the setup by following official integration, but it just throwing class not found error. Can anyone share the way fwd to fix this issue

chat-server.php
_____________
<?php
namespace ChatServer;
use Ratchet\Http\HttpServer;
use Ratchet\WebSocket\WsServer;
use Ratchet\Server\IoServer;
use MyApp\Chat;

require dirname(__DIR__) . '/vendor/autoload.php';

 $server = IoServer::factory(
     new HttpServer(
         new WsServer(
             new Chat()
         )
     ),
     8080
 );

$server->run();

Error:
______
PHP Fatal error:  Uncaught Error: Class 'Ratchet\Server\IoServer' not found in /var/www/html/reactchat/chat-server.php:10
